### ISSUE TITLE
hi is thare any chance to increase nonce?

### ISSUE THREAD

**Issue by gsngsn123** [tudor199/Web3Arbitrage#2]
hi is thare any chance to increase nonce?

because lot of transaction faild due to low nonce is it possible to increase error example below

ARBITRAGE_FOUND at 16-03-2022 at 11:16:28: USDT/WETH on QuickSwap -> SushiSwap
Amounts: 3.1642182822149536 -> 3.18070036805238
Profit: 0.016482085837426688 WETH
EXCEPTION in Worker: {'code': -32000, 'message': 'nonce too low'}!
Traceback (most recent call last):
  File "C:\Users\vkart\Desktop\bot\alchemy\alchemy\manager\worker.py", line 57, in start
    self.web3.eth.sendRawTransaction(signedTransaction.rawTransaction)
  File "C:\Users\vkart\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\eth.py", line 788, in send_raw_transaction
    return self._send_raw_transaction(transaction)
  File "C:\Users\vkart\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\vkart\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "C:\Users\vkart\AppData\Local\Programs\Python\Python39\lib\site-packages\web3\manager.py", line 171, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'nonce too low'}

**Comment by tudor199** [comment]
Hello, Nonce shouldn't be too low, unless you make manual transactions on that account before some arbitrage opportunity is found.
The nonce is synced in the initialization, and it will increment by 1 every time an arbitrage opportunity is found, in order to save  time (not looking for nonce every time an arbitrage opportunity is found).
You can also fetch the nonce before the transaction at line 48 in worker.
